name: klinik_hoaks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.11
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_provinsi_jawa_timur.png
    - assets/hero1.png
    - assets/hero2.png
    - assets/hero3.png
    - assets/hoaks.png
    - assets/fakta.png
    - assets/onboarding/step1.png
    - assets/onboarding/step2.png
    - assets/onboarding/step3.png
    - assets/rekap.png
